MAX_PIXELS=1204224 CUDA_VISIBLE_DEVICES=0,1,2,3 NPROC_PER_NODE=4 swift sft \
  --model_type qwen2_5_vl \
  --model models/Qwen2.5-VL-3B-Instruct \
  --freeze_aligner false \
  --train_type full \
  --dataset data/Multimodal-Cold-Start.json \
  --num_train_epochs 3 \
  --per_device_train_batch_size 4 \
  --per_device_eval_batch_size 4 \
  --gradient_accumulation_steps 8 \
  --save_total_limit 2 \
  --eval_steps 200 \
  --save_steps 200 \
  --output_dir output \
  --system 'sys_prompt.txt' \
  --gradient_checkpointing_kwargs '{"use_reentrant": false}' \
  --deepspeed zero2 \
  --save_only_model false \
  --report_to tensorboard swanlab \
  --swanlab_project 'rl-with-cold-start' \
  --swanlab_exp_name 'qwen2.5vl-3b-sft' \
  --swanlab_mode cloud \